version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - '.dev.env'
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    command: pnpm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdb:/data

volumes:
  postgresdb_data:
  redisdb:
    driver: local
