version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data1:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdb:/data

volumes:
  postgres_data1:
  redisdb:
    driver: local
